### ISSUE TITLE
Subfolders or Dynamic Subfolders

### ISSUE THREAD

**Issue by AbbeyDesign** [amici-infotech/craft-super-pdf#14]
Is there a way when saving these pdfs to a folder other than craft's to create subfolders? And if so, is there a way to do this dynamically at the template level?

eg
MyPDFs (superpdf asset folder)
--User1
-----one.pdf
-----two.pdf
--User2
-----one.pdf
JoesPDFs
-User5
-----one.pdf etc

**Comment by amici-infotech** [comment]
Sure it is. There is 2 ways to do so.

- First one would be to edit Craft's plugin setting and mention your volume and folder. (Where you can pass `storage` as volume to store files to storage folder instead of any assets folder.
- Second would be to pass it in pdf settings. Example:

```
{% set html %}
    <h1>This is a basic example</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>
{% endset %}

{% set settings = {
    filename: "My_PDF",
    type: 'object',

    volume: "uploads",
    folder: "folder1/cache",
} %}

{% set object = craft.superpdf.html(html, settings) %}
<p>{{ object.getUrl }}</p>
<iframe src="{{ object.getUrl }}" width="500" height="600"></iframe>
```
Where `volume: "uploads"` is my filesystem (volume) handle. Note that dynamic folder paths are not working right now with `storage` volume. it will only work with filesystem volume at the moment. in future, we will add feature where dynamic path works with `storage` folder too.

**Comment by AbbeyDesign** [comment]
Perfetto, grazie
