### ISSUE TITLE
Can't get custom fonts to show in PDF

### ISSUE THREAD

**Issue by danfathom** [amici-infotech/craft-super-pdf#20]
Hi,

I'm having some issues getting my font to show in the PDF document. Are you able to see what i'm doing wrong?

Here is how i've got my Super PDF settings set up:

{% set html %}
	{% include "_partials/_price-list-pdf" %}
{% endset %}

{% set settings = {
    filename: entry.slug ~ '-' ~ town ~ '-' ~ parentCounty,
    type: 'url',
    fontDir: "/Applications/MAMP/htdocs/website-name/craft/web/assets/uploads/fonts/",
    tempDir: "/Applications/MAMP/htdocs/website-name/craft/web/assets/uploads/fonts/"
} %}
{% set priceListUrl = craft.superpdf.html(html, settings) %}

Within the '_partials/_price-list-pdf.twig' file i've got the following:

`<style type="text/css">
        @font-face {
            font-family: 'Raleway';
            font-style: normal;
            font-weight: 300;
            src: url({{siteUrl}}assets/font/Raleway-Regular.tiff) format('truetype');
        }
        .pdf-doc h1, .pdf-doc h2, .pdf-doc h3, .pdf-doc td, .pdf-doc p {
        	font-family: 'Raleway', sans-serif !important;
        }
    </style>`

I'm sure there is something i'm doing wrong. Please let me know.

Many thanks,
Dan

**Comment by amici-infotech** [comment]
I think there maybe multiple issues. 

- 1st could be to load ttf file instead of tiff file.
- 2nd could be that you are using local env with SSL?
- 3rd could be folder not exists or not have permission to write. (could you try give 777 permission to /tmp folder and use /tmp folder there for test?) fontDir, and tmpDir are just temp directory that reads your font and saves converted files to these folders. you may not need them inside your website folder.

You can create config/super-pdf.php file to store these config. for example:

```
<?php

use craft\helpers\App;
use Craft;

return [
    'fontDir' => '/tmp',
    'tempDir' => '/tmp',
    'defaultPaperSize' => 'A4',

    'httpContext' => [
        'ssl' => [
            'verify_peer' => false,
            'allow_self_signed' => true,
            'verify_peer_name' => false
        ]
    ]
];
```
